title: Bruno Belarmino
header-img: img/home-bg.jpg
email: bb.belarmino@gmail.com
description: "Blog destinado a tecnologias web e mobile"
baseurl: ""
url: "http://www.brunobelarmino.com.br"
twitter_username: brbelarmino
github_username:  brunobelarmino

markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["Readme.md", "Gemfile", "Gemfile.lock", "CNAME", "_followup"]